lane :test do
  upload_to_qawolf(
    file_path: "./fastlane/fastlane-test-app-debug.apk",
    executable_file_basename: "fastlane_test"
  )
  notify_deploy_qawolf(
    workspace_id: ENV.fetch("QAWOLF_WORKSPACE_ID", nil),
    environment: "Staging",
    sha: "random_sha",
    executable_environment_key: "ANDROID_APP",
    variables: {
      HELLO: "WORLD"
    }
  )
end
