lane :test do
  upload_to_qawolf(
    file_path: "./fastlane/fastlane-test-app-debug.apk"
  )
  notify_deploy_qawolf(
    deployment_type: "android",
    run_input_path: "bad.apk",
    variables: {
      HELLO: "WORLD",
      RUN_INPUT_PATH: "bad123.apk"
    }
  )
end
