name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Install dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle check || bundle install --jobs=4 --retry=3
      - name: Run tests
        run: bundle exec rake
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
